version: '3.8'
services:
  proj1:
    container_name: proj1
    image: proj1
    build: 
      context: ./proj1
      dockerfile: Dockerfile
    restart: always
    volumes: 
      - ./proj1/src/:/app/proj1/src
    ports: 
      - 3333:3333
  proj2:
    container_name: proj2
    image: proj2
    build: 
      context: ./proj2
      dockerfile: Dockerfile
    restart: always
    volumes: 
      - ./proj2/src/:/app/proj2/src
    ports: 
      - 4444:4444